# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 21:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.BooleanField(default=None)),
                ('morn_temp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('day_temp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('night_temp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('date', models.IntegerField(default=0)),
            ],
        ),
    ]
