# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.IntegerField(default=1505603296.0),
        ),
    ]
