# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 23:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20170916_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=12),
        ),
    ]
