# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20170916_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='event',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
