# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_weather_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='conditions',
            field=models.BooleanField(),
        ),
    ]
